# Generated by Django 2.2.7 on 2019-11-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='product name',
            new_name='product_name',
        ),
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='stock',
            name='product_pic',
            field=models.ImageField(default='item.png', upload_to='products'),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stock',
            name='seller',
            field=models.CharField(default='sahara', max_length=100),
        ),
    ]
