# Generated by Django 2.2.7 on 2019-11-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='cat',
            field=models.CharField(default='', max_length=50),
        ),
    ]
