# Generated by Django 2.2.7 on 2019-11-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191123_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='product-name',
            new_name='product_name',
        ),
    ]
