# Generated by Django 2.2.7 on 2019-11-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20191123_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='product_pic',
            field=models.ImageField(default='sahara/sahara-2.png', upload_to='products'),
        ),
    ]
