# Generated by Django 2.2.7 on 2019-11-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_stock_product_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='product_pic',
            field=models.ImageField(default='sahara/item.png', upload_to='products'),
        ),
    ]
