# Generated by Django 2.2.7 on 2019-11-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20191124_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='product_pic',
            field=models.ImageField(default='item.png', upload_to='products'),
        ),
    ]
