# Generated by Django 2.2.7 on 2019-11-25 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
    ]
