# Generated by Django 2.2.7 on 2019-11-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191126_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='username@sahara.com', max_length=254),
        ),
    ]
