# Generated by Django 2.2.7 on 2019-11-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
