# Generated by Django 2.2.7 on 2019-11-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20191126_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='sahara-2.png', upload_to='profile_pics'),
        ),
    ]
